export const products = [
    {
      id: 1,
      name: "Classic Leather Watch",
      details: "Leather strap, steel case.",
      oldPrice: 799,
      price: 499,
      gender: "Male",
      bestselling: false,
      latest: true,
      featured: true,
      sale: false,
      unisex: false,
      img: "../assets/asset-1.png",
      quantity: 1,
    },
    {
      id: 2,
      name: "Digital Sports Watch",
      details: "Water-resistant, stopwatch.",
      oldPrice: 699,
      price: 399,
      gender: "Female",
      bestselling: true,
      latest: true,
      featured: false,
      sale: true,
      unisex: true,
      img: "../assets/asset-2.png",
      quantity: 1,
    },
    {
      id: 3,
      name: "Elegant Gold Watch",
      details: "Rose gold, minimalist.",
      oldPrice: 699,
      price: 449,
      gender: "Female",
      bestselling: false,
      latest: true,
      featured: true,
      sale: false,
      unisex: false,
      img: "../assets/asset-3.png",
      quantity: 1,
    },
    {
      id: 4,
      name: "Fitness Tracker Watch",
      details: "Tracks heart rate, sleep.",
      oldPrice: 799,
      price: 499,
      gender: "Female",
      bestselling: true,
      latest: false,
      featured: false,
      sale: false,
      unisex: true,
      img: "../assets/asset-4.png",
      quantity: 1,
    },
    {
      id: 5,
      name: "Luxury Chrono Watch",
      details: "Gold finish, chronograph.",
      oldPrice: 899,
      price: 499,
      gender: "Male",
      bestselling: false,
      latest: false,
      featured: false,
      sale: false,
      unisex: false,
      img: "../assets/asset-5.png",
      quantity: 1,
    },
    {
      id: 6,
      name: "Casual Analog Watch",
      details: "Lightweight, analog.",
      oldPrice: 599,
      price: 399,
      gender: "Male",
      bestselling: true,
      latest: false,
      featured: true,
      sale: true,
      unisex: true,
      img: "../assets/asset-6.png",
      quantity: 1,
    },
    {
      id: 7,
      name: "Royals Golden Watch",
      details: "Bluetooth, fitness tracking.",
      oldPrice: 799,
      price: 499,
      gender: "Male",
      bestselling: true,
      latest: true,
      featured: true,
      sale: false,
      unisex: false,
      img: "../assets/asset-7.png",
      quantity: 1,
    },
    {
      id: 8,
      name: "Stainless Steel Watch",
      details: "Steel body, classic.",
      oldPrice: 699,
      price: 499,
      gender: "Female",
      bestselling: false,
      latest: false,
      featured: false,
      sale: true,
      unisex: false,
      img: "../assets/asset-8.png",
      quantity: 1,
    },
    {
      id: 9,
      name: "Golden Charm Watch",
      details: "Golden, charm bracelet.",
      oldPrice: 699,
      price: 499,
      gender: "Female",
      bestselling: true,
      latest: false,
      featured: false,
      sale: false,
      unisex: false,
      img: "../assets/asset-9.png",
      quantity: 1,
    },
    {
      id: 10,
      name: "Hybrid Smartwatch",
      details: "Analog and smart features.",
      oldPrice: 699,
      price: 499,
      gender: "Male",
      bestselling: false,
      latest: true,
      featured: true,
      sale: false,
      unisex: true,
      img: "../assets/asset-10.png",
      quantity: 1,
    },
    {
      id: 11,
      name: "Minimalist Black Watch",
      details: "Matte black design.",
      oldPrice: 599,
      price: 399,
      gender: "Male",
      bestselling: false,
      latest: false,
      featured: false,
      sale: true,
      unisex: false,
      img: "../assets/asset-11.png",
      quantity: 1,
    },
    {
      id: 12,
      name: "Pearl Bracelet Watch",
      details: "Pearl bracelet, small dial.",
      oldPrice: 699,
      price: 449,
      gender: "Male",
      bestselling: true,
      latest: false,
      featured: true,
      sale: false,
      unisex: true,
      img: "../assets/asset-12.png",
      quantity: 1,
    },
    {
      id: 13,
      name: "Adventure Watch",
      details: "Shock-resistant, compass.",
      oldPrice: 799,
      price: 499,
      gender: "Male",
      bestselling: false,
      latest: true,
      featured: false,
      sale: false,
      unisex: true,
      img: "../assets/asset-13.png",
      quantity: 1,
    },
    {
      id: 14,
      name: "Vintage Pocket Watch",
      details: "Classic pocket watch.",
      oldPrice: 799,
      price: 499,
      gender: "Female",
      bestselling: false,
      latest: false,
      featured: false,
      sale: false,
      unisex: false,
      img: "../assets/asset-14.png",
      quantity: 1,
    },
    {
      id: 15,
      name: "Diamond Rose Watch",
      details: "Diamond bezel, luxury.",
      oldPrice: 999,
      price: 499,
      gender: "Female",
      bestselling: true,
      latest: false,
      featured: true,
      sale: false,
      unisex: false,
      img: "../assets/asset-15.png",
      quantity: 1,
    },
    {
      id: 16,
      name: "Digital LED Watch",
      details: "LED display, touch controls.",
      oldPrice: 699,
      price: 399,
      gender: "Female",
      bestselling: true,
      latest: false,
      featured: true,
      sale: true,
      unisex: true,
      img: "../assets/asset-16.png",
      quantity: 1,
    },
    {
      id: 17,
      name: "Solar Powered Watch",
      details: "Eco-friendly, solar powered.",
      oldPrice: 799,
      price: 499,
      gender: "Female",
      bestselling: false,
      latest: true,
      featured: true,
      sale: true,
      unisex: true,
      img: "../assets/asset-17.png",
      quantity: 1,
    },
    {
      id: 18,
      name: "Design Fashion Watch",
      details: "Unique design, stylish.",
      oldPrice: 799,
      price: 499,
      gender: "Female",
      bestselling: true,
      latest: false,
      featured: false,
      sale: true,
      unisex: false,
      img: "../assets/asset-18.png",
      quantity: 1,
    },
    {
      id: 19,
      name: "Rugged Military Watch",
      details: "Military-grade, night vision.",
      oldPrice: 799,
      price: 499,
      gender: "Male",
      bestselling: false,
      latest: false,
      featured: true,
      sale: false,
      unisex: true,
      img: "../assets/asset-19.png",
      quantity: 1,
    },
    {
      id: 20,
      name: "Kids Learning Watch",
      details: "Colorful, educational.",
      oldPrice: 499,
      price: 399,
      gender: "Male",
      bestselling: true,
      latest: false,
      featured: false,
      sale: true,
      unisex: true,
      img: "../assets/asset-20.png",
      quantity: 1,
    },
  ];
  